### PR TITLE
Header bug fixed

### LINKED ISSUE #690: Navigation bar increases in height upon viewing the intermediate values table
To recreate: Click on "Intermediate Values" in the header.

image

### PR DESCRIPTION
**Pull request by mvarnum**
Unwanted header resizing no longer occurs -- moved assignments-list and intermediate-table div outside of the header div.

Consolidated popup classes in analysis_style.css to 'popup_frame,' 'popup_content', and 'popup_header' to reduce redundancy.

### CODE REVIEW

**Comment by amgrubb** [comment]
@mvarnum There is no issue associated with this PR. Can you include a screenshot to help explain what the problem was?
Thanks!

**Comment by Vbeany** [comment]
Most of the code was repeated code so there was no major change and the extra height from the bar is fixed, looks good 👍.

**Review by Vbeany — DISMISSED** [review]
Most of the code was repeated code so there was no major change and the extra height from the bar is fixed, looks good 👍.

**Review by Vbeany — APPROVED** [review]
This branch is up to date with develop now and there are no problems.

**Pull request merged**
