### PR TITLE
Fix pagination in next state window for 4+ digit numbers

### LINKED ISSUE #667: Page selection for Next State disappears with large numbers
Screen Shot 2022-06-22 at 11 42 46 AM

### PR DESCRIPTION
**Pull request by Emkung**
fixed the issue where in the next state window when the number of states the user selects exceeds over 1000 the user has to scroll to the side to find the arrow to go next 

Fixed #667

### CODE REVIEW

**Review by mollyd13 — DISMISSED** [review]
Code is well formatted but could use some comments. Next state is working as expected and the issue seems to be fixed. Looks good!

**Review by emruckle — DISMISSED** [review]
Code is clear and well commented. Fixed the next state issue. Did not break simulate single path or loading/saving functions or other next state functionality.

**Review by mollyd13 — APPROVED** [review]
Code looks great and is well commented!

**Review by emruckle — APPROVED** [review]
Code is clear and well commented. Fixed the next state issue. Did not break simulate single path or loading/saving functions or other next state functionality.

**Pull request merged**
