### PR TITLE
Moved onclick event to onFunctions.js

### LINKED ISSUE #359: Go through keyboardFunctions.js
Determine if the functions work, how they work, and if they need their own separate file.
Move the window.onclick event to onFunctions.js

### PR DESCRIPTION
**Pull request by YesugenB**
Copy paste functions work

### CODE REVIEW

**Review by leshghi — COMMENTED** [review]
This looks good to me - but thoughts on moving the keyboard functions to the onFunctionsBothWindows file? Just to consolidate non tool-specific related functions.

**Comment by YesugenB** [comment]
Do you mean moving all of keyboardFunctions.js to onFunctionsBothWindows and then deleting the empty file?

**Comment by leshghi** [comment]
> Do you mean moving all of keyboardFunctions.js to onFunctionsBothWindows and then deleting the empty file?

Yup!

**Review by leshghi — APPROVED** [review]
Looks good to me!

**Pull request merged**
