### PR TITLE
Updated Increasing and Decreasing Functions for Path Constraints

### PR DESCRIPTION
**Pull request by amgrubb**
#23 Fixed
Also started to work on #19 but not finished yet.

### CODE REVIEW

**Comment by Akira83** [comment]
Hello Alicia, I test this model and didn't work. Is the frontend sending something wrong to the backend? Let me know so I can fix it.
increasetest

[increaseTest.json.txt](https://github.com/amgrubb/BloomingLeaf/files/1242159/increaseTest.json.txt)

**Comment by amgrubb** [comment]
Ok, looking into it.

**Comment by amgrubb** [comment]
It doesn't appear to have anything to do with the increase/decrease changes.

**Comment by amgrubb** [comment]
One error in the file is it says:
    "currentState": "",
should be:
    "currentState": "0",

**Comment by amgrubb** [comment]
These two elements are new:
    "initialAssignedEpoch": "",
    "initialValueTimePoints": "",
What are they?

**Comment by amgrubb** [comment]
The error occurs on TroposCSPAlgorithm line ~118
`if (this.spec.getInitialValueTimePoints().length != this.spec.getInitialValues()[0].length)`
this.spec.getInitialValues() returns null, so the initial values are not being set.

This is a new / different bug.

**Pull request merged**
