### PR TITLE
Corrected branch for syntax check Issue #12

### PR DESCRIPTION
**Pull request by g2hchang**
Completed issue #12, which allows user to check if their constraint links are validly assigned to its destination node. For example, if more than 2 nodes pointing to same destination node have different constraint values, then this means it's an invalid link combinations. This feature informs user whether their constraint links combination are valid/not valid.

 **1. User create links.**
screen shot 2017-11-14 at 7 58 13 pm
**2. Select Analysis button, then it triggers to check if links are valid and if not, it highlights all the sets of links that are invalidly combined. Also, it returns error messages and suggestions.**
screen shot 2017-11-14 at 7 52 12 pm

screen shot 2017-11-14 at 7 52 18 pm

**3. If there are more than two groups of links that are invalidly assigned then it will highlight these links as well.**
screen shot 2017-11-14 at 8 02 57 pm

screen shot 2017-11-14 at 8 03 02 pm

**4. If clicked on "Go back to Model View" button, it will return to Model view.**
screen shot 2017-11-14 at 7 52 18 pm

### CODE REVIEW

**Comment by g2hchang** [comment]
I need to fix something, please don't merge yet.

**Comment by g2hchang** [comment]
It's not ready to be merged.

**Comment by amgrubb** [comment]
A correction, the contribution links (++,--, -, + etc.) can be merged with decomposition links (and/or). So this is actually valid.

screen shot 2017-11-18 at 4 35 00 pm

I know, it doesn't really make sense.

**Comment by amgrubb** [comment]
Let me know when you have made this correction. :)

**Pull request merged**
