### PR TITLE
Fixes Two Chart Bugs

### LINKED ISSUE #560: elementInspector chart doesn't clear when you change the initial satisfaction val of an intention
On backbone-refactor. If you console.log the chart after you change an intention's init sat value it still shows the previous function segments even though those function segments have been removed from the intention

### LINKED ISSUE #567: the logic for stochastic-constant function segments is wrong
the chart doesn't change when you change the constant function segment and the stochastic segment changes to no value
image

### PR DESCRIPTION
**Pull request by i-m-foster**
Closes #560 and #567

### CODE REVIEW

**Review by krhablutzel — CHANGES_REQUESTED** [review]
The code looks great! Please update your PR to merge into `sep21-bugs`, then you'll be set to merge

**Comment by YesugenB** [comment]
Can you change the base branch from develop to sep21-bugs? I agree, I think you can delete resetChartDatasets

**Review by amgrubb — APPROVED** [review]

**Comment by amgrubb** [comment]
Please look into if you can delete `resetChartDatasets`. If not, Squash and Merge.

**Review by YesugenB — APPROVED** [review]
Looks good

**Review by krhablutzel — APPROVED** [review]
Looks great!

**Pull request merged**
