### PR TITLE
Solved #592

### PR DESCRIPTION
**Pull request by Domily11**
Added a function in ElementInspector that destroyed associated constraint of intentions that were previously evolving functions

### CODE REVIEW

**Comment by Domily11** [comment]
@amgrubb would destroying all the associated constraints like this work or would you like me to keep the constraint if the new function type is also an evolving function?

**Comment by amgrubb** [comment]
@Domily11 We agreed that if you change the evolving function, it resets all the values associated with that intention in the Intermediate Values Table and the Absolute & Relative Assignments Table.

**Comment by Domily11** [comment]
@i-m-foster Hey Irene, gonna need you to hold off this review for a bit, the bug apparently wasn't completely fixed ugh

**Review by i-m-foster — APPROVED** [review]
it looks good to me!

**Pull request merged**
